export const locales = ["en", "ja", "es", "ko", "pt-br"];

export const localeNames = {
  en: "English",
  ja: "日本語",
  es: "Español",
  ko: "한국어",
  "pt-br": "Português (Brasil)",
};

export const content = {
  en: {
    nav: { experience: "Experience", support: "Support", privacy: "Privacy", terms: "Terms" },
    appStore: "View on the App Store",
    heroTitle: "A quiet place to return to.",
    heroBody: "Dhara brings gently evolving sound, animation, and Momu together for moments of rest and calm focus.",
    heroNote: "No account. No setup. Start at your own pace.",
    experienceTitle: "Sound and motion that keep gently changing.",
    experienceBody: "Choose a sound, an animation, and a duration, then settle in. Dhara generates the experience in real time.",
    headphones: "Headphones are recommended for hearing the subtle shifts in the sound.",
    trustTitle: "Private by design.",
    trustBody: "No account, advertising, analytics, or tracking.",
    preview: "Try a 30-second playback preview.",
    purchase: "One-time purchase. No subscription.",
    availability: "For iPhone. Requires iOS 17.6 or later.",
    comingSoon: {
      title: "Coming to the App Store soon.",
      body: "Dhara is planned for release on October 1, 2026.\n\nThe App Store link will be enabled when the release is live.",
      back: "Back to Dhara",
    },
    menu: "Open menu", close: "Close menu", language: "Language", phoneAlt: "Dhara running on iPhone",
  },
  ja: {
    nav: { experience: "体験", support: "サポート", privacy: "プライバシー", terms: "利用規約" },
    appStore: "App Storeで見る",
    heroTitle: "静けさに戻る\nための場所。",
    heroBody: "Dharaは、ゆるやかに変化し続ける音とアニメーション、Momuを組み合わせ、休息や穏やかな集中のための時間をつくります。",
    heroNote: "アカウントも複雑な設定もなく、自分のペースで始められます。",
    experienceTitle: "ゆるやかに変化し\n続ける、音と動き。",
    experienceBody: "サウンド、アニメーション、時間を選んだら、あとはゆっくりと。Dharaはその場で体験を生み出します。",
    headphones: "音の細かな移ろいを味わうには、ヘッドホンの使用をおすすめします。",
    trustTitle: "プライバシーを大切に。",
    trustBody: "アカウント、広告、アクセス解析、トラッキングはありません。",
    preview: "30秒の無料再生をお試しいただけます。",
    purchase: "買い切りです。サブスクリプションではありません。",
    availability: "iPhone対応。iOS 17.6以降が必要です。",
    comingSoon: {
      title: "App Storeでまもなく公開します。",
      body: "Dharaは2026年10月1日に公開予定です。\n\nリリース開始後にApp Storeへのリンクを有効にします。",
      back: "Dharaに戻る",
    },
    menu: "メニューを開く", close: "メニューを閉じる", language: "言語", phoneAlt: "iPhoneで動作するDhara",
  },
  es: {
    nav: { experience: "Experiencia", support: "Soporte", privacy: "Privacidad", terms: "Términos" },
    appStore: "Ver en el App Store",
    heroTitle: "Un lugar tranquilo al que volver.",
    heroBody: "Dhara combina sonido y animación que evolucionan suavemente con Momu para crear momentos de descanso y concentración serena.",
    heroNote: "Sin cuenta ni configuración complicada. Empieza a tu ritmo.",
    experienceTitle: "Sonido y movimiento que cambian suavemente.",
    experienceBody: "Elige un sonido, una animación y una duración, y tómate tu tiempo. Dhara genera la experiencia en tiempo real.",
    headphones: "Se recomienda usar audífonos para percibir los cambios sutiles del sonido.",
    trustTitle: "Privacidad desde el diseño.",
    trustBody: "Sin cuenta, publicidad, analíticas ni seguimiento.",
    preview: "Prueba una reproducción gratuita de 30 segundos.",
    purchase: "Una sola compra. Sin suscripción.",
    availability: "Para iPhone. Requiere iOS 17.6 o posterior.",
    comingSoon: {
      title: "Próximamente en App Store.",
      body: "Dhara tiene previsto su lanzamiento para el 1 de octubre de 2026.\n\nEl enlace a App Store se activará cuando el lanzamiento esté disponible.",
      back: "Volver a Dhara",
    },
    menu: "Abrir menú", close: "Cerrar menú", language: "Idioma", phoneAlt: "Dhara en un iPhone",
  },
  ko: {
    nav: { experience: "경험", support: "지원", privacy: "개인정보 처리방침", terms: "이용약관" },
    appStore: "App Store에서 보기",
    heroTitle: "고요함으로 돌아가는 공간.",
    heroBody: "Dhara는 잔잔하게 변화하는 사운드와 애니메이션, Momu를 통해 휴식과 차분한 집중을 위한 시간을 만듭니다.",
    heroNote: "계정이나 복잡한 설정 없이, 나만의 속도로 시작하세요.",
    experienceTitle: "잔잔하게 계속 변화하는 소리와 움직임.",
    experienceBody: "사운드, 애니메이션, 시간을 선택한 뒤 편안히 머물러 보세요. Dhara는 경험을 실시간으로 만들어 냅니다.",
    headphones: "사운드의 섬세한 변화를 느끼려면 헤드폰 사용을 권장합니다.",
    trustTitle: "처음부터 개인정보 보호를 고려했습니다.",
    trustBody: "계정, 광고, 분석 또는 추적이 없습니다.",
    preview: "30초 무료 재생을 체험해 보세요.",
    purchase: "한 번만 구매하면 됩니다. 구독이 아닙니다.",
    availability: "iPhone용. iOS 17.6 이상이 필요합니다.",
    comingSoon: {
      title: "App Store에서 곧 만나요.",
      body: "Dhara는 2026년 10월 1일 출시 예정입니다.\n\n출시가 시작되면 App Store 링크를 활성화합니다.",
      back: "Dhara로 돌아가기",
    },
    menu: "메뉴 열기", close: "메뉴 닫기", language: "언어", phoneAlt: "iPhone에서 실행 중인 Dhara",
  },
  "pt-br": {
    nav: { experience: "Experiência", support: "Suporte", privacy: "Privacidade", terms: "Termos" },
    appStore: "Ver na App Store",
    heroTitle: "Um lugar tranquilo para voltar.",
    heroBody: "Dhara combina sons e animações que evoluem suavemente com Momu para criar momentos de descanso e foco tranquilo.",
    heroNote: "Sem conta ou configuração complicada. Comece no seu ritmo.",
    experienceTitle: "Som e movimento que continuam mudando suavemente.",
    experienceBody: "Escolha um som, uma animação e uma duração e fique à vontade. Dhara gera a experiência em tempo real.",
    headphones: "Recomendamos o uso de fones de ouvido para perceber as mudanças sutis do som.",
    trustTitle: "Privacidade desde o início.",
    trustBody: "Sem conta, publicidade, análise ou rastreamento.",
    preview: "Experimente uma reprodução gratuita de 30 segundos.",
    purchase: "Compra única. Sem assinatura.",
    availability: "Para iPhone. Requer iOS 17.6 ou posterior.",
    comingSoon: {
      title: "Em breve na App Store.",
      body: "O lançamento do Dhara está previsto para 1º de outubro de 2026.\n\nO link da App Store será ativado quando o lançamento estiver disponível.",
      back: "Voltar ao Dhara",
    },
    menu: "Abrir menu", close: "Fechar menu", language: "Idioma", phoneAlt: "Dhara em um iPhone",
  },
};
